// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/map": {
            "get": {
                "description": "Position et dernière disponibilité de toutes les stations (sans pagination).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Toutes les stations pour la carte",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.MapStationResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/stations": {
            "get": {
                "description": "Stations paginées, filtrables par ville, avec la dernière disponibilité connue.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Liste les stations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtre par nom de ville",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Taille de page (défaut 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Décalage (défaut 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/stations/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Détail d'une station",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Identifiant interne de la station",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/stations/{id}/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Historique de disponibilité d'une station",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Identifiant interne de la station",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Début (RFC3339, défaut il y a 24h)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fin (RFC3339, défaut maintenant)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/stations/{id}/prediction": {
            "get": {
                "description": "Moyenne par (jour de semaine, tranche de 30 min) en heure locale Europe/Paris.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Prédiction de disponibilité d'une station",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Identifiant interne de la station",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Instant cible (RFC3339, défaut maintenant)",
                        "name": "at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PredictionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HistoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StatusResponse"
                    }
                },
                "from": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "api.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StationResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.MapStationResponse": {
            "type": "object",
            "properties": {
                "bikes_available": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "docks_available": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.PredictedPoint": {
            "type": "object",
            "properties": {
                "bikes_available": {
                    "type": "integer"
                },
                "docks_available": {
                    "type": "integer"
                },
                "samples": {
                    "type": "integer"
                }
            }
        },
        "api.PredictionResponse": {
            "type": "object",
            "properties": {
                "at": {
                    "type": "string"
                },
                "predicted": {
                    "$ref": "#/definitions/api.PredictedPoint"
                },
                "profile": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SlotResponse"
                    }
                },
                "slot": {
                    "type": "integer"
                },
                "station_id": {
                    "type": "integer"
                },
                "weekday": {
                    "type": "integer"
                }
            }
        },
        "api.SlotResponse": {
            "type": "object",
            "properties": {
                "avg_bikes": {
                    "type": "number"
                },
                "avg_docks": {
                    "type": "number"
                },
                "minutes": {
                    "type": "integer"
                },
                "samples": {
                    "type": "integer"
                },
                "slot": {
                    "type": "integer"
                }
            }
        },
        "api.StationResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "station_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/api.StatusResponse"
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "bikes_available": {
                    "type": "integer"
                },
                "bikes_disabled": {
                    "type": "integer"
                },
                "docks_available": {
                    "type": "integer"
                },
                "docks_disabled": {
                    "type": "integer"
                },
                "is_installed": {
                    "type": "boolean"
                },
                "is_renting": {
                    "type": "boolean"
                },
                "is_returning": {
                    "type": "boolean"
                },
                "last_reported": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Vélo Aggregator API",
	Description:      "Disponibilité temps réel de vélos en libre-service, multi-villes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
